import Providers from "./providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Oura Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
