import { getServerSession } from "next-auth/next";
import { authOptions } from "../pages/api/auth/[...nextauth]";

import Providers from "./providers";
import "./globals.css";
import { Navbar } from "./Navbar";

export const metadata = {
  title: "Oura Demo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="font-mono">
        <Navbar />
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
